EI_API_KEY=ei_1db759d69a3ebdf68c566a2d0b009d7e5be6b5fb1dd51e56
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
